// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpMGw3XhA-QxmWmw8-or0zwMnwP5zUu8',
    appId: '1:347899038680:web:2261f15fe3806d48c080ad',
    messagingSenderId: '347899038680',
    projectId: 'inclassact18',
    authDomain: 'inclassact18.firebaseapp.com',
    storageBucket: 'inclassact18.firebasestorage.app',
    measurementId: 'G-57LKT21LTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMQRKxwhbyHZ-TBmtgt07UXN3Bb_N2MQ',
    appId: '1:347899038680:android:035b61bb8d797d87c080ad',
    messagingSenderId: '347899038680',
    projectId: 'inclassact18',
    storageBucket: 'inclassact18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrTfP6c2hTuPSUM2ncbru1vtDB3D37ay0',
    appId: '1:347899038680:ios:e91fc97c37d5658bc080ad',
    messagingSenderId: '347899038680',
    projectId: 'inclassact18',
    storageBucket: 'inclassact18.firebasestorage.app',
    iosBundleId: 'com.example.inclassact18',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrTfP6c2hTuPSUM2ncbru1vtDB3D37ay0',
    appId: '1:347899038680:ios:e91fc97c37d5658bc080ad',
    messagingSenderId: '347899038680',
    projectId: 'inclassact18',
    storageBucket: 'inclassact18.firebasestorage.app',
    iosBundleId: 'com.example.inclassact18',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpMGw3XhA-QxmWmw8-or0zwMnwP5zUu8',
    appId: '1:347899038680:web:7ecda63ea5f400a3c080ad',
    messagingSenderId: '347899038680',
    projectId: 'inclassact18',
    authDomain: 'inclassact18.firebaseapp.com',
    storageBucket: 'inclassact18.firebasestorage.app',
    measurementId: 'G-68E6JHBMNN',
  );
}
